{{- range $i, $agentpool := .Values.agentpools }}
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedMachinePool
metadata:
  name: {{ $agentpool.name }}
spec:
  name: {{ $agentpool.name }}
  scaling:
    minSize: {{ $agentpool.scaling.minSize }}
    maxSize: {{ $agentpool.scaling.maxSize }}
  additionalTags:  
    {{- range $additionalTags := $agentpool.additionalTags }}
    {{ $additionalTags.key }}: {{ $additionalTags.value }}
    {{- end }}
  osDiskSizeGB: {{ $agentpool.osDiskSizeGB }}
  sku: {{ $agentpool.sku }}
  availabilityZones:
      {{- range $agentpool.availabilityZones }}
      - {{ .  | quote }}
      {{- end }}    
  nodeLabels: 
   {{- range $nodeLabels := $agentpool.nodeLabels }}
    {{ $nodeLabels.key }}: {{ $nodeLabels.value }}
   {{- end }}
  taints: 
   {{- range $taints := $agentpool.taints }}
    - key: {{ $taints.key }}
      value: {{ $taints.value }}
      effect: {{ $taints.effect }}
   {{- end }}
  mode: {{ $agentpool.mode }}
  maxPods: {{ $agentpool.maxPods }}
  osDiskType : {{ $agentpool.osDiskType }}
  enableUltraSSD : {{ $agentpool.enableUltraSSD }}
  osType : {{ $agentpool.osType }}
  enableNodePublicIP : {{ $agentpool.enableNodePublicIP }}
  nodePublicIPPrefixID : {{ $agentpool.nodePublicIPPrefixID }}
  scaleSetPriority : {{ $agentpool.scaleSetPriority }}
  scaleDownMode : {{ $agentpool.scaleDownMode }}
  spotMaxPrice : {{ $agentpool.spotMaxPrice }}
  kubeletConfig : {{ $agentpool.kubeletConfig }}
  kubeletDiskType : {{ $agentpool.kubeletDiskType }}
  linuxOSConfig : {{ $agentpool.linuxOSConfig }}
  subnetName : {{ $agentpool.subnetName }}
  enableFIPS : {{ $agentpool.enableFIPS }}
  enableEncryptionAtHost : {{ $agentpool.enableEncryptionAtHost }}

  
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: {{ $agentpool.name }}
spec:
  clusterName: {{ $.Values.cluster.name }}
  replicas: {{ $agentpool.nodecount }}
  template:
    metadata: {}
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: {{ $.Values.cluster.name }}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AzureManagedMachinePool
        name: {{ $agentpool.name }}
        namespace: {{ $.Release.Namespace }}
      version: {{ $.Values.controlplane.kubernetes_version }}
---
{{- end }}

